"""
Tabular instantiation of MBOM (Yu et al., NeurIPS 2022, "Model-Based
Opponent Modeling") as an alternative decision-maker, for stateless repeated
matrix games. Matches the ARAMARL Agent interface, mirroring loqa_agent.py /
pola_agent.py.

MBOM has three ingredients (paper Sections 4.1-4.2):
 (1) a level-0 Imagined Opponent Policy (IOP) phi_0, learned by MLE from the
     opponent's observed actions;
 (2) *recursive imagination*: using the environment model, level-m IOP is the
     opponent's best response to the agent's best response to level-(m-1) IOP,
     giving a hierarchy {phi_0, ..., phi_{M-1}} of "improving opponent policies"
     -- exactly iterated best response / recursive reasoning;
 (3) *Bayesian mixing*: the IOPs are linearly combined,
     pi_mix(.|s) = sum_m alpha_m phi_m(.|s)   (eq. 6),
     with alpha_m the posterior probability p(m | a^o) that the observed
     opponent action was generated by level-m IOP, smoothed by a moving
     average (the non-parametric "IOPs mixer").
 The agent then best-responds to pi_mix.

In a stateless 2x2 game the "environment model" is just the payoff bimatrix,
which we estimate online from observed play (the honest tabular analog of
MBOM's learned environment model), and each rollout best response reduces to
maximizing the immediate expected reward. Everything else -- the recursive
imagination hierarchy and the Bayesian IOP mixer -- follows the paper.

This mirrors, in a lightweight tabular form, the two principles our own
framework is built on: recursive (level-k) reasoning and Bayesian mixing of
opponent models. It is included as an *alternative DM* to benchmark our
scheme against a recent deep method built on the same ideas.
"""

import numpy as np
from numpy.random import choice

from agent import Agent


def softmax(x):
    z = np.exp(x - np.max(x))
    return z / z.sum()


class MBOMAgent(Agent):
    """
    MBOM decision-maker for a stateless repeated matrix game.

    Conventions (matching ARAMARL): in update(obs, actions, rewards, new_obs),
    actions[0]/rewards[0] are this agent's own, actions[1]/rewards[1] are the
    opponent's. Reward estimates are indexed R[a, b] (a = own action, b =
    opponent action) for the agent and Ro[a, b] for the opponent.
    """

    def __init__(self, action_space, enemy_action_space, n_states=1,
                 learning_rate=0.1, epsilon=0.05, gamma=0.96,
                 M=3, tau=0.5, phi_lr=0.15, mix_decay=0.7):
        Agent.__init__(self, action_space)
        self.enemy_action_space = enemy_action_space
        self.epsilon = epsilon
        self.M = M                    # number of IOP levels (0..M-1)
        self.tau = tau                # bounded-rationality temperature (BRs)
        self.phi_lr = phi_lr          # level-0 IOP exp-smoother rate
        self.mix_decay = mix_decay    # moving-average rate of the IOP mixer

        nA = len(action_space)
        nB = len(enemy_action_space)

        # Estimated payoff bimatrix (the "environment model"), running means
        self.R = np.zeros((nA, nB))   # own reward R[a, b]
        self.Ro = np.zeros((nA, nB))  # opponent reward Ro[a, b]
        self.counts = np.zeros((nA, nB))

        # Level-0 IOP: predicted opponent action distribution (uniform prior)
        self.phi0 = np.ones(nB) / nB

        # Bayesian-mixing weights over IOP levels (uniform init, as in paper)
        self.alpha = np.ones(M) / M

        self._last_iops = None        # IOP hierarchy from the last act()

    # -- recursive imagination --------------------------------------------
    def _agent_br(self, q):
        """Agent best-response distribution to opponent distribution q."""
        return softmax((self.R @ q) / self.tau)

    def _opp_br(self, p):
        """Opponent best-response distribution to agent distribution p."""
        return softmax((p @ self.Ro) / self.tau)

    def _imagine(self):
        """Build the IOP hierarchy {phi_0, ..., phi_{M-1}} (paper Sec. 4.1)."""
        iops = [self.phi0.copy()]
        for _ in range(1, self.M):
            p_me = self._agent_br(iops[-1])       # agent BR to previous IOP
            iops.append(self._opp_br(p_me))       # opponent BR to that
        return iops

    # -- Agent interface ----------------------------------------------------
    def act(self, obs=None):
        iops = self._imagine()
        self._last_iops = iops
        q_mix = np.tensordot(self.alpha, np.array(iops), axes=(0, 0))  # eq. 6
        q_mix = q_mix / q_mix.sum()

        if np.random.rand() < self.epsilon:
            return choice(self.action_space)
        values = self.R @ q_mix                    # best-respond to pi_mix
        return self.action_space[int(np.argmax(values))]

    def update(self, obs, actions, rewards, new_obs):
        a, b = actions          # own action, opponent action
        rA, rB = rewards        # own reward, opponent reward

        # Update the estimated payoff bimatrix (environment model)
        self.counts[a, b] += 1
        c = self.counts[a, b]
        self.R[a, b] += (rA - self.R[a, b]) / c
        self.Ro[a, b] += (rB - self.Ro[a, b]) / c

        # Update the level-0 IOP by exponential smoothing (online MLE)
        onehot = np.zeros(len(self.enemy_action_space))
        onehot[b] = 1.0
        self.phi0 = (1 - self.phi_lr) * self.phi0 + self.phi_lr * onehot

        # Bayesian mixing update: posterior over which IOP generated action b,
        # smoothed by a moving average (the non-parametric IOPs mixer, eq. 7)
        if self._last_iops is not None:
            like = np.array([iop[b] for iop in self._last_iops]) + 1e-8
            post = like * self.alpha
            post /= post.sum()
            self.alpha = (self.mix_decay * self.alpha
                          + (1 - self.mix_decay) * post)
            self.alpha /= self.alpha.sum()


if __name__ == '__main__':
    # Sanity check 1: against a FIXED opponent that mostly defects in Chicken,
    # MBOM should best-respond by conceding (playing C), and the mixer should
    # favour the level-0 IOP (a fixed opponent is perfectly predicted by phi_0).
    np.random.seed(0)
    R = np.array([[0., -2.], [1., -4.]])    # own reward, 0=C 1=D
    Ro = R.T.copy()                          # symmetric roles
    ag = MBOMAgent([0, 1], [0, 1], tau=0.5)
    q_fixed = 0.15                            # opponent cooperates 15% -> mostly D
    coop_count = 0
    N = 20000
    for t in range(N):
        a = ag.act()
        b = 0 if np.random.rand() < q_fixed else 1
        rA = R[a, b]; rB = Ro[a, b]
        ag.update(None, (a, b), (rA, rB), None)
        if t >= N - 5000 and a == 0:
            coop_count += 1
    print('P(MBOM cooperates | mostly-defecting fixed opp), last 5000:',
          round(coop_count / 5000, 3), '(expect close to 1 - epsilon)')
    print('estimated own payoff R:\n', np.round(ag.R, 2))
    assert coop_count / 5000 > 0.8, 'MBOM failed to best-respond to fixed opp'
    assert abs(ag.alpha.sum() - 1.0) < 1e-9
    for iop in ag._imagine():
        assert abs(iop.sum() - 1.0) < 1e-9 and (iop >= 0).all()

    # Sanity check 2 (isolated Bayesian-mixing test): with two clearly
    # distinct IOPs, feeding observations consistent with one level must shift
    # the mixer's weight toward that level.
    ag2 = MBOMAgent([0, 1], [0, 1])
    ag2.M = 2
    ag2.alpha = np.array([0.5, 0.5])
    ag2._last_iops = [np.array([0.9, 0.1]), np.array([0.1, 0.9])]  # lvl0 says C
    a0 = ag2.alpha[0]
    for _ in range(30):
        ag2._last_iops = [np.array([0.9, 0.1]), np.array([0.1, 0.9])]
        ag2.update(None, (0, 0), (0.0, 0.0), None)   # observe opp action 0 (C)
    print('mixer weight on level-0 after observing C repeatedly:',
          round(ag2.alpha[0], 3), '(started 0.5, IOP-0 predicts C)')
    assert ag2.alpha[0] > a0, 'Bayesian mixer failed to discriminate IOPs'

    # Sanity check 3: IBR collapse in Chicken vs. non-collapse in a
    # competitive game (Matching Pennies), which motivates the game choice.
    def iop_spread(Rm):
        a = MBOMAgent([0, 1], [0, 1], tau=0.5)
        a.R, a.Ro = Rm, Rm.T.copy()
        a.phi0 = np.array([0.5, 0.5])
        iops = np.array(a._imagine())
        return np.abs(iops - iops[0]).max()
    MP = np.array([[1., -1.], [-1., 1.]])            # matching pennies (zero-sum)
    print('IOP spread  Chicken:', round(iop_spread(R), 3),
          ' Matching-Pennies:', round(iop_spread(MP), 3))
    print('sanity checks passed')
